/*! Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,m=!0,p=null,q=!1;function r(a){return function(){return a}}var u=["search!"],v=3,x="BAIDU_DUP_replacement",z="http://dup.baidustatic.com/painter/",A=document,B={},C=0,D=1,E=2,F=3,G=4,H=5;function I(a){var b=J(a),d=b[0],b=b[1];this.id=a;this.name=b;this.uri=K(b);this.ma=!b;this.status=C;d&&b&&(this.ra=L(N(d+"!"))||{load:function(){}});this.r=[]}var Q=window.BAIDU_DUP_require||function(a,b,d){O(a,function(){for(var c=[],d=0;d<a.length;d++)c[d]=L(N(a[d]));P(b)&&b.apply(window,c)},d)};
function O(a,b,d){var c=a.length;if(0===c)b();else for(var j=c,f=0;f<c;f++)(function(a){function h(){if(a.status<E)k();else{for(var h=a.r,c=[],b=0;b<h.length;b++){var t=h[b];t&&N(t).status<F&&c.push(t)}0===c.length?k():O(c,k,d)}}function k(){a&&a.status<F&&(a.status=F);0===--j&&b()}var c=a.ra;c&&(c.normalize&&(a.name=c.normalize(a.name,K)),c.name2url&&(a.uri=c.name2url(a.name)));a.status<E?c&&P(c.load)?c.load(a.name,Q,function(h){R(a.id,[],function(){return h});k()}):S(a,h,d):h()})(N(a[f]))}
var T={},U={},V={};function S(a,b,d){a.status=D;V[a.id]?b():U[a.id]?T[a.id].push(b):(U[a.id]=m,T[a.id]=[b],d?(b=a.uri,a=A.createElement("script"),a.charset="utf-8",a.async=m,a.src=b,b=A.getElementsByTagName("head")[0]||A.body,b.insertBefore(a,b.firstChild)):A.write('<script charset="utf-8" src="'+a.uri+'"><\/script>'))}var R=window.BAIDU_DUP_define||function(a,b,d){var c=N(a);c.status<E&&(c.r=b,c.factory=d,c.status=c.ma?F:E);if(U[a]){delete U[a];V[a]=m;b=T[a];for(delete T[a];a=b.shift();)a()}};
function L(a){if(!a)return p;if(a.status>=G)return a.L;if(a.status<F&&a.L===l)return p;a.status=G;for(var b=[],d=0;d<a.r.length;d++)b[d]=L(N(a.r[d]));var c=d=a.factory;P(d)&&(c=d.apply(window,b));a.status=H;return a.L=c}function K(a){return/^https?:\/\//.test(a)?a:z+a+".js"}function N(a){return B[a]||(B[a]=new I(a))}function J(a){var b,d=a?a.indexOf("!"):-1;-1<d&&(b=a.slice(0,d),a=a.slice(d+1,a.length));return[b,a]}function P(a){return"[object Function]"===Object.prototype.toString.call(a)}
R("util/lang",[],function(){function a(a){for(var c={},b="Array Boolean Date Error Function Number RegExp String".split(" "),f=0,e=b.length;f<e;f++)c["[object "+b[f]+"]"]=b[f].toLowerCase();return a==p?"null":c[Object.prototype.toString.call(a)]||"object"}var b=Object.prototype.hasOwnProperty;return{D:b,a:a,getAttribute:function(a,c){for(var b=a,f=c.split(".");f.length;){if(b===l||b===p)return;b=b[f.shift()]}return b},T:function(d){if("object"!==a(d))return"";var c=[],j;for(j in d)b.call(d,j)&&c.push(j+
"="+encodeURIComponent(d[j]));return c.join("&")},k:function(b){var c=[];switch(a(b)){case "object":c=Array.prototype.slice.call(b);break;case "array":c=b;break;case "number":case "string":c.push(b)}return c},unique:function(a){for(var c=[],b={},f=a.length,e=0;e<f;e++){var h=a[e];b[h]||(c[c.length]=h,b[h]=m)}return c},removeItem:function(a,c){for(var b=[].slice.call(a),f=b.length-1;0<=f;f--)b[f]===c&&b.splice(f,1);return b},pa:function(){}}});
R("util/browser",["util/lang"],function(a){var b={},d=navigator.userAgent,c=window.RegExp;/msie (\d+\.\d)/i.test(d)&&(b.O=document.documentMode||+c.$1);/opera\/(\d+\.\d)/i.test(d)&&(b.opera=+c.$1);/firefox\/(\d+\.\d)/i.test(d)&&(b.Ca=+c.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(d)&&!/chrome/i.test(d)&&(b.Qa=+(c.$1||c.$2));if(/chrome\/(\d+\.\d)/i.test(d)){b.$=+c.$1;var j;try{j="scoped"in document.createElement("style")}catch(f){j=q}j&&(b.wa=m)}try{/(\d+\.\d)/.test(a.getAttribute(window,
"external.max_version"))&&(b.Na=+c.$1)}catch(e){}a="Android iPad iPhone Linux Macintosh Windows".split(" ");c="";for(j=0;j<a.length&&!(c=a[j],d.match(RegExp(c.toLowerCase(),"i")));j++);b.platform=c;return b});
R("util/dom",["util/lang"],function(a){function b(a){try{if(a&&"object"===typeof a&&a.document&&"setInterval"in a)return m}catch(b){}return q}function d(a,c){c=2===arguments.length?c:a.parent;return a!=c||!b(a)}function c(a,b){for(var b=2===arguments.length?b:a.parent,h=0;10>h++&&d(a,b);){var k;try{k=!!a.parent.location.toString()}catch(c){k=q}if(!k)return m;a=a.parent}return 10<=h}function j(a){return 9===a.nodeType?a:a.ownerDocument||a.document}return{c:function(b,c){return"string"===a.a(b)&&0<
b.length?(c||window).document.getElementById(b):b.nodeName&&(1===b.nodeType||9===b.nodeType)?b:p},na:b,q:d,F:c,da:j,u:function(a){a=j(a);return a.parentWindow||a.defaultView||p},h:function(a){a=b(a)?a.document:j(a);return"CSS1Compat"===a.compatMode?a.documentElement:a.body},A:function(b,e){1===arguments.length&&"number"===a.a(arguments[0])&&(e=arguments[0],b=l);for(var e=e||10,h=window,k=0;k++<e&&d(h)&&!c(h)&&(!b||!b(h));)h=h.parent;return h}}});
R("util/style",["util/lang","util/dom","util/browser"],function(a,b,d){function c(a,k){if(!a)return"";var c="",c=-1<k.indexOf("-")?k.replace(/[-][^-]{1}/g,function(a){return a.charAt(1).toUpperCase()}):k.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()}),d=b.u(a);if(d&&d.getComputedStyle){if(d=d.getComputedStyle(a,p))return d.getPropertyValue(k)||d.getPropertyValue(c)}else if(a.currentStyle)return d=a.currentStyle,d[k]||d[c];return""}function j(a){var k={top:0,left:0};if(a===b.h(a))return k;
var d=b.da(a),g=d.body,d=d.documentElement;a.getBoundingClientRect&&(a=a.getBoundingClientRect(),k.left=Math.floor(a.left)+Math.max(d.scrollLeft,g.scrollLeft),k.top=Math.floor(a.top)+Math.max(d.scrollTop,g.scrollTop),k.left-=d.clientLeft,k.top-=d.clientTop,a=c(g,"borderLeftWidth"),g=c(g,"borderTopWidth"),a=parseInt(a,10),g=parseInt(g,10),k.left-=isNaN(a)?2:a,k.top-=isNaN(g)?2:g);return k}function f(a,b){var d=c(a,"margin"+b).toString().toLowerCase().replace("px","").replace("auto","0");return parseInt(d,
10)||0}function e(c){for(var k=b.u(c),i=100;c&&c.tagName;){var g=100;if(d.O){if(5<d.O)try{g=parseInt(a.getAttribute(c,"filters.alpha.opacity"),10)||100}catch(e){}i=i>g?g:i}else{try{g=100*(k.getComputedStyle(c,p).opacity||1)}catch(o){}i*=g/100}c=c.parentNode}return 0===i?0:i||100}return{La:c,Ia:j,B:function(a){var c=b.c(a);if(!c)return q;a=j(c);c=b.u(c);if(!c)return a;for(var d=0;c!==c.parent&&10>d++&&!b.F(c)&&c.frameElement;){var g=j(c.frameElement);a.left+=g.left;a.top+=g.top;c=c.parent}return a},
Da:f,Ha:function(a,c){var d=b.c(a),g=d.offsetWidth;c&&(g+=f(d,"Left")+f(d,"Right"));return g},Ga:function(a,c){var d=b.c(a),g=d.offsetHeight;c&&(g+=f(d,"Top")+f(d,"Bottom"));return g},Fa:e,Ea:function(a){for(var c=b.c(a),a=b.u(c),c=e(c),d=0;10>d++&&b.q(a)&&!b.F(a);){var g=a.frameElement?e(a.frameElement):100,c=c*(g/100);a=a.parent}return c},ia:function(a){try{var c=b.h(a||window).scrollWidth;if(c||0===c)return c}catch(d){}return-1},ha:function(a){try{var c=b.h(a||window).scrollHeight;if(c||0===c)return c}catch(d){}return-1},
t:function(a){try{var c=b.h(a||window).clientWidth;if(c||0===c)return c}catch(d){}return-1},s:function(a){try{var c=b.h(a||window).clientHeight;if(c||0===c)return c}catch(d){}return-1},Ka:function(a){var c=b.h(a);return a.pageYOffset||c.scrollTop},Ja:function(a){var c=b.h(a);return a.pageXOffset||c.scrollLeft}}});
R("util/url",["util/dom"],function(a){return{N:function(a,d,c){a=a.match(RegExp("(\\?|&|#)"+d+"=([^&#]*)(&|#)?"));d="";a&&(d=a[2]);c&&(d=decodeURIComponent(d));return d},C:function(b){var b=a.A(b),d="";a.q(b)&&(d=b.document.referrer);return d=d||b.location.href}}});
R("util/event",["util/dom"],function(a){return{bind:function(b,d,c){if(b=a.na(b)?b:a.c(b))if(b.addEventListener)b.addEventListener(d,c,q);else if(b.attachEvent)b.attachEvent("on"+d,c);else{var j=b["on"+d];b["on"+d]=function(){j&&j.apply(this,arguments);c.apply(this,arguments)}}return b}}});
R("util/cookie",["util/lang"],function(a){return{get:function(a,d){var c=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie);return c?d?decodeURIComponent(c[2]):c[2]:""},set:function(b,d,c,j){var f=c.expires;"number"===a.a(f)&&(f=new Date,f.setTime(+f+c.expires));document.cookie=b+"="+(j?encodeURIComponent(d):d)+(c.path?"; path="+c.path:"")+(f?"; expires="+f.toGMTString():"")+(c.domain?"; domain="+c.domain:"")}}});
R("util/data",["util/lang","util/dom"],function(a,b){function d(c,b,d){var d=d?h:f,e;if("string"===a.a(c)){for(c=c.split(".");c.length;)e=c.shift(),d[e]=c.length?d[e]!==l?d[e]:{}:b,d=d[e];e=b}return e}function c(c,b){var d=b?h:f,e;"string"===a.a(c)&&(e=a.getAttribute(d,c));return e}function j(a,b,h){if(!a||!b)return q;var e=c(a)||{};switch(h){case "+1":h=e[b]||0;e[b]=++h;break;default:e[b]=parseInt(h,10)}d(a,e);return e[b]}var f={},e=b.A(),h=e.BAIDU_DUP_info||(e.BAIDU_DUP_info={});return{l:function(a,
c){var b=window;return b[a]?b[a]:b[a]=c},m:function(a){var c=window,b=c[a];c[a]=l;return b},i:d,d:c,S:function(c,b){var d=b?h:f;switch(a.a(c)){case "string":for(var e=c.split(".");e.length;){var o=e.shift();if(e.length&&d[o]!==l)d=d[o];else return delete d[o],m}}return q},J:function(a,c){return j(a,c,"+1")},Oa:function(a,c,b){return j(a,c,b)},count:j,ca:function(a,b){return!a||!b?q:(c(a)||{})[b]||0},va:function(a,b){if(!a||!b)return q;var h=c("pageConfig")||{};h[a]=b;d("pageConfig",h);return m},ba:function(a){return!a?
q:(c("pageConfig")||{})[a]}}});
R("util/storage",[],function(){function a(a,c,b){if(d)try{d.setItem(a,b?encodeURIComponent(c):c)}catch(h){}}function b(a,c){if(d){var b=d.getItem(a);return c&&b?decodeURIComponent(b):b}return p}var d;try{d=window.localStorage}catch(c){}return{Aa:function(){var c=q;try{d.removeItem("BAIDU_DUP_storage_available"),a("BAIDU_DUP_storage_available","1"),b("BAIDU_DUP_storage_available")&&(c=m),d.removeItem("BAIDU_DUP_storage_available")}catch(f){}return c},setItem:a,getItem:b,W:function(c,f,e){if(d){f=e?
encodeURIComponent(f):f;e=b(c)||"";try{a(c,e+((e&&"|")+f))}catch(h){}}},V:function(c,f,e){if(d)if(f=e?encodeURIComponent(f):f,e=b(c)||"",e=e.replace(RegExp(f+"\\|?","g"),"").replace(/\|$/,""))try{a(c,e)}catch(h){}else d.removeItem(c)}}});
R("util/log",["util/lang","util/event","util/storage"],function(a,b,d){function c(a,c){var b=new Image,d="BAIDU_DUP_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=p;b=window[d]=p;c&&c(j,a,m)};b.src=a}var j="BAIDU_DUP_log_storage";return{Ma:c,Pa:function(){var a=d.getItem(j);if(a)for(var a=a.split("|"),b=0,h=a.length;b<h;b++)c(decodeURIComponent(a[b]),d.V)},G:function(f){var f="object"===a.a(f)?f:{},e=f.url||
"http://cbjslog.baidu.com/log",h=f.option||"now",f=a.T(f.data||{}),e=e+((0<=e.indexOf("?")?"&":"?")+f+(f?"&":"")+"rdm="+ +new Date);switch(h){case "now":c(e);break;case "block":break;default:d.W(j,e,m),b.bind(window,"unload",function(){c(e,d.V)})}}}});R("util","util/lang,util/dom,util/style,util/url,util/event,util/cookie,util/data,util/storage,util/log,util/browser".split(","),function(a,b,d,c,j,f,e,h,k,i){return{lang:a,b:b,style:d,url:c,event:j,cookie:f,data:e,Ra:h,log:k,Z:i}});
R("biz",["util","slot"],function(a,b){function d(c,b){var d=/^[0-9a-zA-Z]+$/;return!c||!d.test(c)||!b?[]:b="array"===a.lang.a(b)?b:Array.prototype.slice.call(arguments,1)}function c(c,b,d){if(!b||!b.length)return q;var d=d||{I:q,Q:q,R:q},i=d.Q?a.data.d(j):{},g=d.I?f:j,i=d.R?{}:a.data.d(g)||i,d={},n;for(n in i)a.lang.D.call(i,n)&&(d[n]="array"===a.lang.a(i[n])?i[n].slice():i[n]);var i=d[c]||[],o=b.length;for(n=0;n<o;n++){var t=b[n];"string"===typeof t&&(t=encodeURIComponent(t),100>=t.length&&(i[i.length]=
t))}if(!i.length)return q;d[c]=a.lang.unique(i);a.data.i(g,d);return m}var j="bizOrientations",f="bizUrgentOrientations";return{K:function(a,b){var k=d.apply(this,arguments);return c(a,k)},X:function(a,b){var k=d.apply(this,arguments);return c(a,k,{I:m,Q:m})},xa:function(a,b){var k=d.apply(this,arguments);return c(a,k,{I:m,R:m})},fa:function(c){var c=Math.max(0,Math.min(c||500,500)),b=[],d=a.data.d(f)||a.data.d(j)||{};if("object"===a.lang.a(d))for(var i in d)a.lang.D.call(d,i)&&(b[b.length]=i+"="+
d[i].join(","));a.data.i(f,l);b.sort(function(a,c){return a.length-c.length});d="";i=b.length;for(var g=0;g<i&&!(d.length+b[g].length>=c);g++)d+=(g?"&":"")+b[g];return d},Y:function(c,d){var f=b.p(),i={},g;for(g in f)if(f.hasOwnProperty(g)){var j=RegExp(d+"_[0-9]","g"),o=a.b.c("BAIDU_DUP_wrapper_"+g),t=q;o&&0<o.firstChild.outerHTML.length&&(t=m);if(d&&j.test(g)||!d)i[g]=t}c.apply(window,[i])}}});
R("preview",["biz","util"],function(a,b){function d(){function a(c){var d=b.url.N;return d(j,"baidu_clb_preview_"+c)||d(j,"baidu_dup_preview_"+c)}var j=b.url.C(),f=a("sid"),e=a("mid"),h=a("vc"),k=+a("ts"),i=p;3E4>=+new Date-k&&(i={U:f,oa:e,za:h});d=function(){return i};return i}return{ja:function(a){var b=[],f=d();f&&a==f.U&&(b.push("mid="+f.oa),b.push("sid="+f.za));return b.join("&")},d:function(){return d()},P:function(a){var d=q;a?/cpro_template=/gi.test(a)&&(b.data.i("#unionPreviewSwitch",m),
d=m):d=!!b.data.d("#unionPreviewSwitch");return d},ka:function(){var a=b.data.d("#unionPreviewData");return a?"prev="+encodeURIComponent(a)+"&pt=union":""},ya:function(a){b.data.i("#unionPreviewData",a)},Ba:function(){b.data.S("#unionPreviewSwitch");b.data.S("#unionPreviewData")}}});
R("slot",["util"],function(a){function b(){for(var a={response:{},holder:"",stack:[],errors:[],status:{}},c=k.length-1;0<=c;c--)a.status[k[c]]=0;return a}function d(a,c){var b=q;"fillAsync"===c&&(b=m);n[a]&&-1!==n[a].stack.join(" ").toLowerCase().indexOf("async")&&(b=m);return b}function c(a,c){if(!a)return"";var b=o+a;c&&(b+="_"+c);return b}function j(a,c,b){if(!a||!c)return q;b===l&&(b=+new Date);return n[a]?(n[a].status[c]=b,m):q}function f(a,c){e(a,"errors",c)}function e(c,b,d){c&&b&&d&&(c=n[c])&&
"array"===a.lang.a(c[b])&&c[b].push(d)}function h(a){return!a?n:n[a]||q}var k="add,create,request,response,render,finish".split(","),i=[],g={},n={},o="BAIDU_DUP_wrapper_";return{add:function(){var c={ids:[],preloadIds:[]},d=a.lang.k(arguments);if(!d.length)return c;for(var d=d.join(",").split(","),o=[],e=[],f=d.length,k=0;k<f;k++){var s=d[k];if(g.hasOwnProperty(s)){var w=s+"_"+g[s],y=h(w).stack||[];if("preload"===y[y.length-1]){c.preloadIds.push(w);continue}g[s]+=1}else g[s]=0;s=s+"_"+g[s];n[s]=new b;
j(s,"add");e.push(s);o.push(s)}i=i.concat(e);c.ids=o;return c},create:function(b,o,h){if(!b||!o)return q;var e=c(b),g=m;if(a.b.c(e))return n[b].holder=e,g;if(d(b,o)){h=h||"";n[b].holder=h;h=a.b.c(h);try{h&&(h.innerHTML='<div id="'+e+'"></div>',n[b].holder=e)}catch(k){f(b,"Failed to insert wrapper"),g=q}}else if(document.write('<div id="'+e+'"></div>'),!a.b.c(e))try{var i=document.getElementsByTagName("script"),w=i[i.length-1];if(w){var y=w.parentNode;if(y){var M=document.createElement("div");M.id=
c(b,"b");y.insertBefore(M,w)}}}catch(W){f(b,"Failed to create backup wrapper")}j(b,"create");return g},aa:d,ea:function(a){return d(a)?"async":"sync"},M:function(b){return!b?"":(b=a.b.c(n[b].holder)||a.b.c(c(b))||a.b.c(c(b,"b")))&&b.id||""},p:h,H:function(a,c){if(!a||!c)return q;return n[a]?(n[a].response=c,j(a,"response"),m):q},n:j,j:f,v:function(a,c){e(a,"stack",c)},z:function(c){c=a.lang.k(c);if(!c.length)return q;var b=[],d={},o;for(o=0;o<i.length;o++)d[i[o]]=o+1;for(o=0;o<c.length;o++){var h=
d[""+c[o]];h===l&&(h=0);b.push(h)}return b},B:function(b){b=a.lang.k(b);if(!b.length)return["-1x-1"];for(var d=[],o=0;o<b.length;o++){var h=b[o],e;try{var g=a.b.c(c(h))||a.b.c(c(h,"b"));if(g){var k=a.style.B(g);k&&(e=[k.top,k.left])}}catch(i){f(h,"Unable to get ps")}e=e?e:[-1,-1];d.push(e.join("x"))}return d}}});
R("api",["slot","util"],function(a,b){return{getDai:a.z,getSlots:a.p,getFillType:a.ea,getFillWrapperId:a.M,setStatus:a.n,addErrorItem:a.j,addStackItem:a.v,bind:b.event.bind,getType:b.lang.a,sendLog:b.log.G,putInfo:b.data.i,getInfo:b.data.d,defineOnce:b.data.l,addCount:b.data.J,getCount:b.data.ca,getConfig:b.data.ba}});
R("param",["slot","preview","biz","util"],function(a,b,d,c){function j(a,c){for(var c=c||0,b=[],d=0,h=a.length;d<h;d++)b.push(a[d].split("_")[c]);return b.join(",")}function f(a){a=a||window.document.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var c=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm|tw|ma|in|vn|name|mx|gd|im)(?:\\.(?:cn|jp|tw|ru|th))?)$","i"));return c?
c[0]:a}var e=window,h=e.document,k=e.screen,i=e.navigator,g=+new Date,n=[{key:"di",value:function(a){return j(a.id)}},{key:"dcb",value:r("BAIDU_DUP_define")},{key:"dtm",value:r("BAIDU_DUP_SETJSONADSLOT")},{key:"dbv",value:function(){var a=c.Z;return a.wa?"1":a.$?"2":"0"}},{key:"dci",value:function(c){for(var b="-1",d={fill:"0",fillOnePiece:"1",fillAsync:"2",preload:"3"},h=0;h<c.id.length;h++){var e=a.p(c.id[h]);if(e){var e=e.stack,g=e.length;if(1<=g){b=d[e[g-1]];break}}}return b}},{key:"dri",value:function(a){return j(a.id,
1)}},{key:"dis",value:function(){var a=0;c.b.q(e)&&(a+=1);c.b.F(e,e.top)&&(a+=2);var b=c.style.t(),d=c.style.s();if(40>b||10>d)a+=4;return a}},{key:"dai",value:function(c){return a.z(c.id).join(",")}},{key:"dds",value:function(){var a=c.data.d("dds");return c.lang.T(a)}},{key:"drs",value:function(){var a={uninitialized:0,loading:1,loaded:2,interactive:3,complete:4};try{return a[h.readyState]}catch(c){return-1}}},{key:"dvi",value:r("1410833010")},{key:"ltu",o:m,value:function(){var a=c.url.C(function(a){var b=
c.style.t(a),a=c.style.s(a);return 400<b&&120<a?m:q});0<a.indexOf("cpro_prev")&&(a=a.slice(0,a.indexOf("?")));return a}},{key:"liu",o:m,value:function(){return c.b.q(e)?h.URL:""}},{key:"ltr",o:m,value:function(){var a=c.b.A(),b="";try{b=a.opener?a.opener.document.location.href:""}catch(d){}return b||a.document.referrer}},{key:"lcr",o:m,value:function(){var a=h.referrer,b=a.replace(/^https?:\/\//,""),b=b.split("/")[0],b=b.split(":")[0],b=f(b),d=f(),e=c.cookie.get("BAIDU_DUP_lcr");if(e&&d===b)return e;
return d!==b?(c.cookie.set("BAIDU_DUP_lcr",a,{domain:d}),a):""}},{key:"ps",value:function(c){return a.B(c.id).join(",")}},{key:"psr",value:function(){return[k.width,k.height].join("x")}},{key:"par",value:function(){return[k.availWidth,k.availHeight].join("x")}},{key:"pcs",value:function(){return[c.style.t(),c.style.s()].join("x")}},{key:"pss",value:function(){return[c.style.ia(),c.style.ha()].join("x")}},{key:"pis",value:function(){return(c.b.q(e)?[c.style.t(),c.style.s()]:[-1,-1]).join("x")}},{key:"cfv",
value:function(){var a=0;if(i.plugins&&i.mimeTypes.length){var c=i.plugins["Shockwave Flash"];c&&c.description&&(a=c.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0")}else if(e.ActiveXObject&&!e.opera)for(c=10;2<=c;c--)try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c);b&&(a=b.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,"."))}catch(d){}return parseInt(a,10)}},{key:"ccd",value:function(){return k.colorDepth||0}},{key:"chi",value:function(){return e.history.length||
0}},{key:"cja",value:function(){return i.javaEnabled().toString()}},{key:"cpl",value:function(){return i.plugins.length||0}},{key:"cmi",value:function(){return i.mimeTypes.length||0}},{key:"cce",value:function(){return i.cookieEnabled||0}},{key:"col",value:function(){return(i.language||i.browserLanguage||i.systemLanguage).replace(/[^a-zA-Z0-9\-]/g,"")}},{key:"cec",value:function(){return(h.characterSet?h.characterSet:h.charset)||""}},{key:"cdo",value:function(){var a=window.orientation;a===l&&(a=
-1);return a}},{key:"tsr",value:function(){var a=0,c=+new Date;g&&(a=c-g);return a}},{key:"tlm",value:function(){return Date.parse(h.lastModified)/1E3}},{key:"tcn",value:function(){return Math.round(+new Date/1E3)}},{key:"tpr",value:function(a){var a=a&&a.max_age?a.max_age:24E4,c=(new Date).getTime(),b,d;try{b=!!window.top.location.toString()}catch(h){b=q}d=b?window.top:window;(b=d.BAIDU_DUP2_pageFirstRequestTime)?c-b>=a&&(b=d.BAIDU_DUP2_pageFirstRequestTime=c):b=d.BAIDU_DUP2_pageFirstRequestTime=
c;return b||""}},{key:"_preview",value:function(a){return b.ja(j(a.id))}},{key:"dpt",value:function(){var a="none";b.P()&&(a="union");return a}},{key:"coa",o:m,value:function(a){var b=a.id,b=b[0].split("_")[0],a={},d=q,h=c.data.d("#novaOpenApi");if(h&&b&&h[b]){var d=m,b=h[b],e;for(e in b)e&&b.hasOwnProperty(e)&&"undefined"!==typeof b[e]&&(a[e]=encodeURIComponent(b[e]).toString())}d&&(a.c01=1);e="";for(var g in a)g&&a.hasOwnProperty(g)&&"undefined"!==typeof a[g]&&(e+="&"+g+"="+a[g]);return e=e.slice(1)}},
{key:"_unionpreview",value:function(){return b.ka()}},{key:"baidu_id",value:r("")},{key:"_orientation",value:function(){return d.fa()}}];return{get:function(a,b){for(var c=[],d=0,e=n.length;d<e;d++){var h;try{var g=n[d],f=g.key,k=g.o,i=g.value,i="function"===typeof i?i(a):i,i=k?encodeURIComponent(i):i;if(b&&b===f)return i;h=f&&0!==f.indexOf("_")?f+"="+i:i}catch(j){h=encodeURIComponent(j.toString()),h=h.slice(0,100)}h&&c.push(h)}c=c.join("&");return c.slice(0,2048)}}});
R("request",["param","slot","util"],function(a,b,d){R("request!",[],{name2url:function(b){return"http://cb.baidu.com/ecom?"+a.get({id:b.split(",")})}});R("batch!",[],{name2url:function(b){return"http://cb.baidu.com/ecom?"+a.get({id:b.split(",")})}});return{send:function(a,j,f){if(!a||!j||f===l)return q;var e=[];if("array"!==d.lang.a(a))b.n(a,"request"),e=["request!"+a];else{for(e=0;e<a.length;e++)b.n(a[e],"request");e=1===a.length?["request!"+a[0]]:["batch!"+a.join(",")]}Q(e,j,f);return m}}});
R("control",["slot","request","preview","util"],function(a,b,d,c){function j(b,d,e){var g=d.deps,f=d.data,j=a.M(b);e&&!j?a.j(b,"HolderNotFound"):g&&(0>g[0].indexOf("clb/")&&a.n(b,"finish"),Q(g,function(d){if("object"===c.lang.a(f)){f.id=b;if(d.hasOwnProperty("validate"))try{var e=d.validate(f);e!==m&&c.log.G({data:{type:e||"ResponseError",errorPainter:g[0],id:b,slotType:f._stype,materialType:f._isMlt,html:!!f._html}})}catch(k){a.j(b,"validateException")}if(d.hasOwnProperty("render"))try{a.n(b,"render"),
d.render(f,j)}catch(i){a.j(b,"RenderException")}else a.j(b,"RenderNotFound")}else a.j(b,"ResponseFormatError")},e))}function f(c,d,e){if(!c)return q;var e=e||"",g=a.add(c),c=g.ids[0]||g.preloadIds[0];if(!c)return q;var f=a.aa(c,d);a.v(c,d);a.create(c,d,e);g.ids.length?b.send(c,function(b){a.H(c,b);j(c,b,f)},f):g.preloadIds.length&&(d=a.p(c).response,j(c,d,f));return m}function e(b){for(var c=0,d=b+"_"+c;0!==a.z([d])[0];){var e=a.p(d);if((e=e&&e.response)&&0===e.deps[0].indexOf("clb/")){var f=e.data,
e=f._isMlt;(0===e&&""!==f._html||e===q&&f._fxp)&&a.n(d,"finish",0)}d=b+"_"+ ++c}if(b!==l&&(b=(c=window.BAIDU_CLB_SLOTS_MAP)&&c[b],b!==l&&(e=b._isMlt,0===e&&""!==b._html||e===q&&b._fxp)))b._done=q}window.BAIDU_CLB_prepareMoveSlot=e;return{fill:function(a){return f(a,"fill")},w:function(a,b){return f(a,"fillAsync",b)},sa:function(){function e(d){b.send(d,function(b){if("array"===c.lang.a(b)){if(b&&b.length===d.length)for(var e=0;e<d.length;e++)a.H(d[e],b[e])}else"object"===c.lang.a(b)&&b&&1===d.length&&
a.H(d[0],b)},q)}var f=c.lang.k(arguments),f=c.lang.unique(f),i=d.d();if(i)for(var g=0,j=f.length;g<j;g++)f[g]==i.U&&(f.splice(g,1),g--);for(f=a.add(f).ids;f.length;){i=f.splice(0,16);for(g=0;g<i.length;g++)a.v(i[g],"preload");e(i)}},ta:e}});
R("global",["control","biz","util","preview"],function(a,b,d,c){function j(a){a=a.split(".");return i[a[0]]+a[1]}function f(){var a=k.BAIDU_DUP;if(!("object"===d.lang.a(a)&&a.push)){if("array"===d.lang.a(a)&&a.length)for(var b=0;b<a.length;b++)e(a[b]);k.BAIDU_DUP=l;d.data.l("BAIDU_DUP",{push:e});d.data.l("BAIDU_DUP_proxy",function(a){if(a)return function(){try{return e([a].concat(d.lang.k(arguments)))}catch(b){0<v--&&d.log.G({data:{type:"ExecuteException",errorName:a,args:d.lang.k(arguments).join("|"),
isQuirksMode:"CSS1Compat"!==document.compatMode,documentMode:document.documentMode||"",readyState:document.readyState||"",message:b.message}})}}});for(b in n)b&&d.lang.D.call(n,b)&&d.data.l(b,k.BAIDU_DUP_proxy(b));h()}}function e(a){if("array"!==d.lang.a(a))return q;var b=a.shift();d.data.J("apiCount",b);return(b=n[b]||o[b]||q)&&b.apply(p,a)}function h(){function a(b){for(var c=0,d=u.length;c<d;c++)if(0===b.indexOf(u[c]))return m;return q}d.data.l("BAIDU_DUP_require",function(b){for(var c=0,d=b.length;c<
d;c++)if(a(b[c]))return;Q.apply(p,arguments)});d.data.l("BAIDU_DUP_define",function(b,c){for(var d=0,e=c.length;d<e;d++)if(a(c[d]))return;R.apply(p,arguments)})}var k=window,i={clb:"BAIDU_CLB_",dan:"BAIDU_DAN_",nova:"cpro",dup:"BAIDU_DUP_"},g=[{f:["clb.fillSlot","clb.singleFillSlot","clb.fillSlotWithSize"],g:["fill"],e:a.fill},{f:["clb.fillSlotAsync"],g:["fillAsync"],e:a.w},{f:["clb.preloadSlots"],g:["preload"],e:a.sa},{f:["clb.prepareMoveSlot"],g:["prepareMove"],e:a.ta},{f:["clb.addOrientation"],
g:["addOrientation"],e:b.K},{f:["clb.addOrientationOnce"],g:["addOrientationOnce"],e:b.X},{f:["clb.setOrientationOnce"],g:["setOrientationOnce"],e:b.xa},{f:["clb.setConfig"],g:["putConfig"],e:d.data.va},{f:["clb.addSlot","clb.enableAllSlots","clb.SETHTMLSLOT"],g:[],e:d.lang.pa},{f:["dup.addSlotStatusCallback"],g:[],e:b.Y}],g=function(a){for(var b={},c={},d=0;d<a.length;d++){for(var e=a[d],f=e.f,g=e.g,e=e.e;f.length;)b[j(f.shift())]=e;for(;g.length;)c[g.shift()]=e}return{qa:b,ua:c}}(g),n=g.qa,o=g.ua;
return{la:function(){var e=d.data.m(j("clb.ORIENTATIONS"));if(e)for(var g in e)Object.prototype.hasOwnProperty.call(e,g)&&b.K(g,e[g]);d.data.i("#novaOpenApi",d.data.m("cproStyleApi"));var h=d.data.m("cproArray");if(h)for(var e=0,i=h.length;e<i;e++)h[e]&&h[e].id&&a.w(h[e].id,"cpro_"+h[e].id);if(h=d.data.m("cpro_mobile_slot")){e=0;for(i=h.length;e<i;e++){var k=h[e],o=k.id,n=d.data.d("#novaOpenApi")||{};n[o]||(n[o]={});for(g in k)g&&"id"!==g&&k.hasOwnProperty(g)&&(n[o][g]=k[g]);d.data.i("#novaOpenApi",
n);h[e]&&h[e].id&&a.w(h[e].id,"cpro_"+h[e].id)}}if(g=d.data.m("cpro_id"))c.P(g)&&(c.ya(g),g="u0"),a.fill(g);a.fill(d.data.m(j("clb.SLOT_ID")));f()}}});R("replacement",["util"],function(a){function b(){var d=a.url.C(),c=a.url.N(d,x,m);b=function(){return c};return c}return{ga:function(){return b()}}});Q(["replacement"],function(a){(a=a.ga())?Q([a]):Q(["global"],function(a){a.la()})});})();
